### ISSUE TITLE
Building element positions shifted

### ISSUE THREAD

**Issue by hlg** [opensourceBIM/WebGL-threeJS#14]
For some IFC models the geometry of single building elements is generated properly, but their position is shifted in an inexplicable way. However other models generate proper geometry throughout.

**Comment by dlabz** [comment]
Some models reuse geometry. 
Use: 
```
geometryInfo.getTransformation()
```
for each instance of geometryData, to get it's transformation matrix.

Cheers

**Comment by dlabz** [comment]
Update:  

To fix this issue, the format of the serialized JSON needs to change a little. 
You COULD transform each object's geometry with it's matrix in the serializer, to preserve the current format, but it will soon be deprecated anyway.

I believe the best format to use is this:

```
{
    "metadata": {
        "version": 4.3,
        "type": "Object",
        "generator": "BIMserver ThreeJS Serializer"
    },
    "geometries": [
        {
            "index" : 123456789, //IfcProduct.GeometryInfo.GeometryData.getOid()
            "type" : "BufferGeometry",
            "data": {
            "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [50,50,50,...]
                    },
                    "normal": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [1,0,0,...]
                    }
            }
    ],
    "materials": [
        {
                "uuid": "62764189-B29B-4D3A-8A0F-67E626F22E0C",
                "type": "MeshPhongMaterial",
                "color": 16777215,
                "ambient": 16777215,
                "emissive": 0,
                "specular": 1118481,
                "shininess": 30
            }
    ],
    "object": {
        "uuid": "B5771EDC-1CDA-4B6F-97E4-B4529CC205FB", //IfcProduct.getGlobalId()
        "type": "Scene",
         "matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
         "children": [
            {
                "uuid": "33FA38D9-0AAC-4657-9BBE-5E5780DDFB2F",
                "name": "Wall 1",
                "type": "IfcWall",
                "geometry": 123456789, //IfcProduct.GeometryInfo.GeometryData.getOid()
                "material": "62764189-B29B-4D3A-8A0F-67E626F22E0C",
                "matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1] //IfcProduct.geometryInfo.getTransformation()
            }
         ]
    }
}
```
There are probably some issues with this format.
One that comes to mind is that IFC / BIMserver don't actually use materials in same way as ThreeJS does.
 
GeometryData also provides per-vertex colors, but in 32bit format, which isn't supported by ThreeJS.

All in all, it's going to be difficult to generate a JSON file that is fully compatible with Loaders provided by ThreeJS.

**Comment by hlg** [comment]
Yes, I was going to update to the [three.js 4 scene format](https://github.com/mrdoob/three.js/wiki/JSON-Object-Scene-format-4). Thanks for the `geometryInfo.getTransformation()` hint, I remember seeing that change rushing by in the commit history. Is there any comprehensive documentation of the current GeometryData interface?

**Comment by dlabz** [comment]
I don't think there's any comprehensive documentation, but I did figure it out, some from BIMsurfer code, and rest by trial and error. 
To get per-vertex colors use:
```
ByteBuffer materialsByteBuffer = ByteBuffer.wrap(geometryData.getMaterials());
materialsByteBuffer.order(ByteOrder.LITTLE_ENDIAN);
FloatBuffer materialsBuffer = materialsByteBuffer.asFloatBuffer();
```
materialsBuffer will have 4 float values per vertex, each representing alpha, r,g,b values.

The biggest compatibility issue is lack of support for 32 bit per-vertex colors in ThreeJS.
Using alpha will require writing a custom vertex shader to show transparency.

**Comment by hlg** [comment]
Updated to three.js JSON model 4 with geometry reuse.
