### ISSUE TITLE
Can you port the ServerPlugin into a Maven project

### ISSUE THREAD

**Issue by hujb2000** [opensourceBIM/WebGL-threeJS#18]
All plugins almost are maven projects except for this.   Can you port the ServerPlugin into a Maven project?

**Comment by rubendel** [comment]
This has now been done in a separate branch: https://github.com/opensourceBIM/WebGL-threeJS/tree/bimserver1.5

The action should not be seen as an intention to revive this plugin, we needed a 1.5 build of this plugin for an older server (1.5.75).
